---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reload caddy
  service:
    name: caddy
    state: reloaded
    enabled: yes

- name: restart caddy
  service:
    name: caddy
    state: restarted
    enabled: yes