---
- name: install and start nginx
  hosts: web
  become: yes

  tasks:
    - name: install nginx
      yum:
        name:
          - nginx
          - certbot-nginx
        state: latest
    - name: copy config for jenkins routing
      copy:
        src: nginx.conf
        dest: '/etc/nginx/nginx.conf'
        mode: preserve
      notify: restart nginx
    - name: start nginx
      service:
        name: nginx
        state: started
  
  handlers:
    - name: restart nginx
      service:
        name: nginx
