- name: import jenkins public pgp keys
  apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
- name: add debian-stable jenkins repo on Debian
  command: sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
- name: update all packages on Debian
  apt: "upgrade=yes update_cache=yes cache_valid_time=86400"
- name: install JDK
  apt: name=openjdk-11-jdk state=present
- name: install Jenkins
  apt: name=jenkins state=present update_cache=yes
  notify: restart nginx

