- include: debian.yml
  when: ansible_os_family == "Debian"
- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: ensure /etc/nginx/conf.d/ directory exists
  file: path=/etc/nginx/conf.d state=directory recurse=yes
- name: copy jenkins nginx config
  template: src=jenkins.conf.j2 dest=/etc/nginx/conf.d/ci.{{ fqdn }}.conf
- name: run systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes
- name: start jenkins
  ansible.builtin.systemd: "name=jenkins state=started"
- name: get initialAdminPassword
  command: sudo cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: initialPassword
- name: print initialAdminPassword
  debug:
    var: initialPassword.stdout_lines
